























                                                                                                                                                                                                                                                    

                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                            document.write("<script type='text/javascript' src='//qwertypay.com/myqwpshop2.js?prod=9239&dosell'></script>");                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                 